SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 300
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
WHITE = (255, 255, 255)
PLAYER_SHOOT_SPEED = 400
SHOT_RADIUS = 5
PLAYER_SHOOT_COOLDOWN = 0.3


ASTEROID_POINTS = {
    ASTEROID_MIN_RADIUS: 100,         # Small asteroids
    ASTEROID_MIN_RADIUS * 2: 50,      # Medium asteroids
    ASTEROID_MIN_RADIUS * 3: 25       # Large asteroids
}